### ISSUE TITLE
unable to decrypt the data using aws-encryption-sdk

### ISSUE THREAD

**Issue by srikanthmaduri3** [aws/aws-encryption-sdk-java#253]
Hi All,
I am facing the below issue while decrypting the data in java. any one Could you please help me on this

java.lang.NoSuchMethodError: com.amazonaws.services.kms.model.DecryptRequest.withKeyId(Ljava/lang/String;)Lcom/amazonaws/services/kms/model/DecryptRequest;
	at com.amazonaws.encryptionsdk.kms.KmsMasterKey.decryptDataKey(KmsMasterKey.java:180) ~[aws-encryption-sdk-java-1.9.0.jar:na]
	at com.amazonaws.encryptionsdk.kms.KmsMasterKeyProvider.decryptDataKey(KmsMasterKeyProvider.java:733) ~[aws-encryption-sdk-java-1.9.0.jar:na]
	at com.amazonaws.encryptionsdk.DefaultCryptoMaterialsManager.decryptMaterials(DefaultCryptoMaterialsManager.java:113) ~[aws-encryption-sdk-java-1.9.0.jar:na]
	at com.amazonaws.encryptionsdk.internal.DecryptionHandler.readHeaderFields(DecryptionHandler.java:610) ~[aws-encryption-sdk-java-1.9.0.jar:na]
	at com.amazonaws.encryptionsdk.internal.DecryptionHandler.<init>(DecryptionHandler.java:109) ~[aws-encryption-sdk-java-1.9.0.jar:na]
	at com.amazonaws.encryptionsdk.internal.DecryptionHandler.create(DecryptionHandler.java:300) ~[aws-encryption-sdk-java-1.9.0.jar:na]
	at com.amazonaws.encryptionsdk.AwsCrypto.decryptData(AwsCrypto.java:523) ~[aws-encryption-sdk-java-1.9.0.jar:na]
	at com.amazonaws.encryptionsdk.AwsCrypto.decryptData(AwsCrypto.java:510) ~[aws-encryption-sdk-java-1.9.0.jar:na]
	at com.amazonaws.encryptionsdk.AwsCrypto.decryptData(AwsCrypto.java:483) ~[aws-encryption-sdk-java-1.9.0.jar:na]

**Comment by lavaleri** [comment]
Hi @srikanthmaduri3

You might see that error if you are running an older version of the AWS SDK. You should use at least v1.11.704 of the aws-java-sdk if you are using the 2.2.0 release of the AWS Encryption SDK for Java.

Can you try upgrading aws-java-sdk and see if you still have this issue?

**Comment by srikanthmaduri3** [comment]
> Hi @srikanthmaduri3
> 
> You might see that error if you are running an older version of the AWS SDK. You should use at least v1.11.704 of the aws-java-sdk if you are using the 2.2.0 release of the AWS Encryption SDK for Java.
> 
> Can you try upgrading aws-java-sdk and see if you still have this issue?

**Comment by srikanthmaduri3** [comment]
Yes,It is issue with sdk version

**Comment by srikanthmaduri3** [comment]
> Hi @srikanthmaduri3
> 
> You might see that error if you are running an older version of the AWS SDK. You should use at least v1.11.704 of the aws-java-sdk if you are using the 2.2.0 release of the AWS Encryption SDK for Java.
> 
> Can you try upgrading aws-java-sdk and see if you still have this issue?

Thank you for the reply
