### ISSUE TITLE
Support EC Algorithms/Keys

### ISSUE THREAD

**Issue by MikeDombo** [aws/aws-encryption-sdk-java#352]
### Problem:

Currently elliptic curve keys do not work due to the "transform" wrapper requiring "RSA/ECB" algorithms which then results in the following stacktrace:

```
Caused by: java.security.InvalidKeyException: No installed provider supports this key: sun.security.ec.ECPublicKeyImpl
	at javax.crypto.Cipher.chooseProvider(Cipher.java:896)
	at javax.crypto.Cipher.init(Cipher.java:1399)
	at javax.crypto.Cipher.init(Cipher.java:1330)
	at com.amazonaws.encryptionsdk.internal.RsaJceKeyCipher.buildWrappingCipher(RsaJceKeyCipher.java:95)
	at com.amazonaws.encryptionsdk.internal.JceKeyCipher.encryptKey(JceKeyCipher.java:89)
```
EC keys are becoming more and more popular so it would be highly beneficial if we could use EC keys with the encryption SDK.

### Solution:

Allow non-RSA/ECB algorithms for the wrapper in order to allow for EC-based algorithms such as "ECIESwithAES" provided by bouncycastle.

### Out of scope:

Is there anything the solution will intentionally NOT address?

[//]: #  (NOTE: If you believe this might be a security issue, please email aws-security@amazon.com instead of creating a GitHub issue. For more details, see the AWS Vulnerability Reporting Guide: https://aws.amazon.com/security/vulnerability-reporting/ )

**Comment by lavaleri** [comment]
Thank you for the feedback @MikeDombo

You are correct that JceMasterKey only supports RSA as an option for an asymmetric wrapping algorithm. We do not have plans to directly add EC support here.

I'm keeping this issue open as a feature request, and we will update this issue if we have updates on support for EC as an option for wrapping algorithm.
