### ISSUE TITLE
Illegal Key Size exception

### ISSUE THREAD

**Issue by m-revetria** [aws/aws-encryption-sdk-java#80]
Hi! I'm getting the exception below in a job in CircleCI when running some unit tests:

```
com.amazonaws.encryptionsdk.exception.AwsCryptoException: java.security.InvalidKeyException: Illegal key size, took 0.267 sec
    at com.amazonaws.encryptionsdk.internal.CipherHandler.cipherData(CipherHandler.java:78)
    at com.amazonaws.encryptionsdk.internal.EncryptionHandler.computeHeaderTag(EncryptionHandler.java:373)
    at com.amazonaws.encryptionsdk.internal.EncryptionHandler.signCiphertextHeaders(EncryptionHandler.java:401)
    at com.amazonaws.encryptionsdk.internal.EncryptionHandler.<init>(EncryptionHandler.java:135)
    at com.amazonaws.encryptionsdk.AwsCrypto.encryptData(AwsCrypto.java:248)
    at com.amazonaws.encryptionsdk.AwsCrypto.encryptString(AwsCrypto.java:305)
    at com.amazonaws.encryptionsdk.AwsCrypto.encryptString(AwsCrypto.java:293)
    at com.amazonaws.encryptionsdk.AwsCrypto.encryptString(AwsCrypto.java:320)
    at <local_code>
    ...
Caused by: java.security.InvalidKeyException: Illegal key size
    at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
    at javax.crypto.Cipher.implInit(Cipher.java:805)
    at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
    at javax.crypto.Cipher.init(Cipher.java:1396)
    at javax.crypto.Cipher.init(Cipher.java:1327)
    at com.amazonaws.encryptionsdk.internal.CipherHandler.cipherData(CipherHandler.java:73)
    ... 71 more
```

That job is running the docker image openjdk:8-jdk and the version used of this SDK is 1.3.5.

The only reference I've found is #1, where the fix seems to be installing JCE but [README](https://github.com/aws/aws-encryption-sdk-java#required-prerequisites) points out it is needed when running Oracle JDK.

Additionally, I have another job running in Circle for the same project using the same configuration, at least it seems so, and there tests are working fine.

**Comment by m-revetria** [comment]
Never mind, I've found that in Circle the failing job was running oracle JDK instead of OpenJDK. Copying the JCE files into java installation folder made it to work.

I'm closing this issue, sorry for any inconvenience this might have caused.
